//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unosquare.Labs.EmbedIO.ExtraTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unosquare.Labs.EmbedIO.ExtraTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;posts&quot;: [
        ///    { &quot;id&quot;: 1, &quot;title&quot;: &quot;json-server&quot;, &quot;author&quot;: &quot;typicode&quot; },
        ///    { &quot;id&quot;: 2, &quot;title&quot;: &quot;embedio&quot;, &quot;author&quot;: &quot;unosquare&quot; },
        ///    { &quot;id&quot;: 3, &quot;title&quot;: &quot;tubular&quot;, &quot;author&quot;: &quot;unosquare&quot; }
        ///  ],
        ///  &quot;comments&quot;: [
        ///    { &quot;id&quot;: 1, &quot;body&quot;: &quot;some comment&quot;, &quot;postId&quot;: 1 },
        ///    { &quot;id&quot;: 2, &quot;body&quot;: &quot;some comment&quot;, &quot;postId&quot;: 2 }
        ///  ]
        ///}.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Hello EmbedIO
        ///
        ///This is just a sample. [Go to help](/help.html).
        ///
        ///* Because I want.
        ///* Because bacon.
        ///
        ///If you are using testing Bearer Tokens, try to access to [secure page](/secure.html).
        ///
        ///[Visita EmbedIO](http://unosquare.github.io/embedio)..
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Hello EmbedIO&lt;/h1&gt;
        ///&lt;p&gt;This is just a sample. &lt;a href=&quot;/help.html&quot;&gt;Go to help&lt;/a&gt;.&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;Because I want.&lt;/li&gt;
        ///    &lt;li&gt;Because bacon.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;p&gt;If you are using testing Bearer Tokens, try to access to &lt;a href=&quot;/secure.html&quot;&gt;secure page&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://unosquare.github.io/embedio&quot;&gt;Visita EmbedIO&lt;/a&gt;.&lt;/p&gt;
        ///
        ///.
        /// </summary>
        internal static string indexhtml {
            get {
                return ResourceManager.GetString("indexhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Secure
        ///
        ///You are using bearer token correctly..
        /// </summary>
        internal static string secure {
            get {
                return ResourceManager.GetString("secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:7777/.
        /// </summary>
        internal static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
    }
}
